#!/bin/bash

./lista-tablas $1 > tbl
cat tbl | grep  -Ev "^tf.*posicion_nave$" | grep -v tf_foto_nave | grep -v tf_act_foto_nave > importar

while read  -r line
do
  echo tabla: $line
  ./importa-una $1 $line
done < importar

rm tbl


